# Generated by Django 2.1.1 on 2018-09-04 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0004_auto_20180904_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='less',
            name='less',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bord.Article'),
        ),
    ]
