# Generated by Django 2.1.1 on 2018-09-04 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0005_auto_20180904_0612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='less',
            old_name='less',
            new_name='lessto',
        ),
    ]
