# Generated by Django 2.1.1 on 2018-09-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0006_auto_20180904_0615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='less',
            old_name='approved_comment',
            new_name='approved_less',
        ),
    ]
