# Generated by Django 2.1.1 on 2018-09-04 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0007_auto_20180904_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='less',
            name='lessto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lesss', to='bord.Article'),
        ),
    ]
