# Generated by Django 2.1.1 on 2018-09-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0008_auto_20180904_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='less',
            name='publishd_date',
        ),
    ]
